### ISSUE TITLE
P1-[4.0 bug hunting]-[Dashboard]-wrong memory usage info for TiKV

### ISSUE THREAD

**Issue by YKG** [tidb-challenge-program/bug-hunting-issue#96]
### 1. What did you do?

- run `tiup playground`
- check `INFORMATION_SCHEMA.CLUSTER_LOAD` table, with filter `DEVICE_NAME='virtual'`
- run `free -b`

### 2. What did you expect to see?

- all services' memory `used` and `free` should be identical or just a little different

### 3. What did you see instead?

- TiDB's and PD's are identical to the output of `free -b`, they are correct
- TiKV's memory `used` and `free` have a big gap compare to the correct values
- TiFlash's should be also wrong, but I have reported the bug in a previous issue

<img width="743" alt="批注 2020-05-25 170949" src="https://user-images.githubusercontent.com/3883644/82798108-ac442f00-9eaa-11ea-97b0-16c4b3256d32.png">

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

 v4.0.0-rc.2

### Addtional notes

- I have read TiKV's code, and the root cause was the memory usage info was retrived from a 3rd party library called `sysinfo`, but `sysinfo` doesn't have a correct implementation.
- I have created a PR to `sysinfo` https://github.com/GuillaumeGomez/sysinfo/pull/317, do we need to waiting for the merge or we need to add a separate patch to TiKV first? @breeswish

**Comment by breezewish** [comment]
@YKG You can make a PR to https://github.com/tikv/sysinfo and we can merge it quickly.

**Comment by breezewish** [comment]
Looks like the usage of TiFlash is not correct as well....

**Comment by YKG** [comment]
@breeswish My PR to sysinfo has been merged, sysinfo upgraded to a minor version, TiKV used the major version, seems like we don't need to do any changes now.

Yes, TiFlash's usage is incorrect. I reported the bug last week, I found TiKV's usage was also incorrect when I tried to find the root cause of TiFlash's yesterday, that's why this issue was created.

@leiysky is working on the issue of TiFlash's. https://github.com/tidb-challenge-program/bug-hunting-issue/issues/91#issuecomment-633553813

**Comment by breezewish** [comment]
@YKG TiKV uses version lock so that the lock file need to be updated.

**Comment by leiysky** [comment]
@breeswish To make the behavior of TiFlash and TiKV consistent, we ported `sysinfo` in TiFlash. Which version of `sysinfo` will you use instead?

**Comment by YKG** [comment]
@leiysky sysinfo version in TiKV `Cargo.toml` is `0.14`, in `Cargo.lock`, its `0.14.1` now. the latest version is `0.14.2` in crates.io. The maintainer of sysinfo has upgraded the version to `0.14.3` in github after merged my PR a few hours ago, but I didn't see the `0.14.3` release in crates.io.

I don't know how crates.io works, do we need to ask sysinfo maintainer to release the new version in crates.io, or the creates.io will pull github repo automatically to create a new release so that we can use `0.14.3`, or we should use https://github.com/tikv/sysinfo first. @breeswish

**Comment by breezewish** [comment]
@YKG You can wait 0.14.3 to be released, or simply specify `git = "....."` to use the current latest git commit.

**Comment by leiysky** [comment]
@YKG Fine. I'll fix TiFlash with your PR in `sysinfo`.

**Comment by YKG** [comment]
@breeswish I just found that in TiKV `release-4.0` branch, `sysinfo` dependency is https://github.com/tikv/sysinfo.git while in master it's `0.14`. It seems like `tikv/sysinfo.git` is not actively maintained, is there any risk to use that in `release-4.0`? Just a reminder. @breeswish 

Because when I working on this PR https://github.com/tikv/tikv/pull/7889, the type `MacAddr` is also related to `sysinfo`
